source 'https://rubygems.org'

gem 'json-ld'
gem 'json-ld-preloaded'
gem 'rdf-rdfa'
gem 'rdf-microdata'
gem 'rdf-reasoner'
gem 'rdf-turtle'
gem 'rspec'
gem 'rake'
gem 'nokogiri', '>= 1.15.7'
gem 'nokogumbo'
gem 'equivalent-xml'

group :debug do
  gem 'byebug'
end
